In [47]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder


In [48]:
# loading csv file
car=pd.read_csv('C://Users//Bhavesh//carprices.csv')
car

Car_Model  Mileage  Sell_price  Age
0                  BMW X5    69000       18000    6
1                  BMW X5    35000       34000    3
2                  BMW X5    57000       26100    5
3                  BMW X5    22500       40000    2
4                  BMW X5    46000       31500    4
5                 Audi A5    59000       29400    5
6                 Audi A5    52000       32000    5
7                 Audi A5    72000       19300    6
8                 Audi A5    91000       12000    8
9   Mercedez Benz C class    67000       22000    6
10  Mercedez Benz C class    83000       20000    7
11  Mercedez Benz C class    79000       21000    7
12  Mercedez Benz C class    59000       33000    5

In [49]:
# creating variable for label encoder
le=LabelEncoder()
carle=car

In [50]:
carle.Car_Model=le.fit_transform(carle.Car_Model)
carle.Car_Model

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     2
10    2
11    2
12    2
Name: Car_Model, dtype: int32

In [51]:
x=carle[['Car_Model','Mileage','Age']]
y=carle.Sell_price

In [52]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[0])



In [53]:
#creating there dummies variable using thi ohe variable
x=ohe.fit_transform(x).toarray()
x

C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0.00e+00, 1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [54]:
#now droping 1 column in order to escape the dummy variable trap
x=x[:,1:]
x

array([[1.00e+00, 0.00e+00, 6.90e+04, 6.00e+00],
       [1.00e+00, 0.00e+00, 3.50e+04, 3.00e+00],
       [1.00e+00, 0.00e+00, 5.70e+04, 5.00e+00],
       [1.00e+00, 0.00e+00, 2.25e+04, 2.00e+00],
       [1.00e+00, 0.00e+00, 4.60e+04, 4.00e+00],
       [0.00e+00, 0.00e+00, 5.90e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 5.20e+04, 5.00e+00],
       [0.00e+00, 0.00e+00, 7.20e+04, 6.00e+00],
       [0.00e+00, 0.00e+00, 9.10e+04, 8.00e+00],
       [0.00e+00, 1.00e+00, 6.70e+04, 6.00e+00],
       [0.00e+00, 1.00e+00, 8.30e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 7.90e+04, 7.00e+00],
       [0.00e+00, 1.00e+00, 5.90e+04, 5.00e+00]])

In [55]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [56]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
model.predict([[1,0,1,69000,6]])

ValueError: shapes (1,5) and (4,) not aligned: 5 (dim 1) != 4 (dim 0)

In [61]:
#mercedes
model.predict([[0,0,45000,4]])

array([34537.77647335])

In [63]:
#bmw
model.predict([[0,1,86000,7]])

array([17818.95045785])

In [64]:
model.score(x,y)

0.9417050937281083