In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits=load_digits()
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [6]:
lr=LogisticRegression()
sv=SVC()
rfc=RandomForestClassifier(n_estimators=40)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=.2)

In [8]:
lr.fit(x_train,y_train)
sv.fit(x_train,y_train)
rfc.fit(x_train,y_train)
print('Logistic regression score',lr.score(x_test,y_test))
print('support vector machine score',sv.score(x_test,y_test))
print('Random Forest score',rfc.score(x_test,y_test))

C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Logistic regression score 0.9583333333333334
support vector machine score 0.39444444444444443
Random Forest score 0.9555555555555556


In [10]:
#so every time we run above code we get different answer 
#so we will use kfold cross validation which divide data uniformmly
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [11]:
# its an example, kfold is implemented 

for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:
#straifield kfold is better than k fold becouse the uniformity of data is more in stratifold
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [17]:
# now we will create a genric function for getting score
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test)

0.39444444444444443

In [33]:
#now we will get the score using stratified fold
lr_score=[]
sv_score=[]
rfc_score=[]

for Train_index,Test_index in folds.split(digits.data,digits.target):
        x_train, x_test, y_train, y_test=digits.data[Train_index],digits.data[Test_index],digits.target[Train_index],digits.target[Test_index]
        lr_score.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))
        sv_score.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
        rfc_score.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [34]:
print(lr_score)
print(sv_score)
print(rfc_score)

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]
[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]
[0.9269102990033222, 0.9499165275459098, 0.924496644295302]


In [39]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target)

C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.89534884, 0.94991653, 0.90939597])

In [41]:
#excercise
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [42]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target)

C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.96078431, 0.92156863, 0.95833333])

In [46]:
cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv='warn')

C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.98039216, 0.96078431, 0.97916667])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)

C:\Users\Bhavesh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([0.98039216, 0.94117647, 0.97916667])