In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
# loadin home price data sets
hp=pd.read_csv('C://Users//Bhavesh//hprice_multi_variable.csv')
hp

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       NaN   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
hp.bedrooms

0    3.0
1    4.0
2    3.0
3    NaN
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [4]:
#calculating median
import math
bedrooms_meadian=math.floor(hp.bedrooms.median())
bedrooms_meadian

4

In [5]:
#now filling the meduan to blank space
hp.bedrooms=hp.bedrooms.fillna(bedrooms_meadian)
hp.bedrooms

0    3.0
1    4.0
2    3.0
3    4.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [6]:
#callimg linear regression of multivariable
reg=linear_model.LinearRegression()
reg.fit(hp[["area","bedrooms","age"]],hp.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
reg.coef_

array([  122.87256289,  6952.97970225, -5166.71560907])

In [8]:
reg.intercept_

284798.80224601174

In [9]:
reg.predict([[3000,4,15]])

array([603727.67559198])

In [10]:
reg.predict([[2600,3,20]])

array([521792.09268801])

In [11]:
#multivariable linear regression task
from word2number import w2n

In [12]:
hir=pd.read_csv('C://Users//Bhavesh//hiring.csv')

In [13]:
hir

experience  test_score_out_of_10  interview_score(out of 10)  salary($)
0        NaN                   8.0                           9      50000
1        NaN                   8.0                           6      45000
2       five                   6.0                           7      60000
3        two                  10.0                          10      65000
4      seven                   9.0                           6      70000
5      three                   7.0                          10      62000
6        ten                   NaN                           7      72000
7     eleven                   7.0                           8      80000

In [14]:
#filling null space
hir.experience=hir.experience.fillna('zero')
#findind median of test score
median=hir.test_score_out_of_10.median()
hir.test_score_out_of_10=hir.test_score_out_of_10.fillna(median)
hir

experience  test_score_out_of_10  interview_score(out of 10)  salary($)
0       zero                   8.0                           9      50000
1       zero                   8.0                           6      45000
2       five                   6.0                           7      60000
3        two                  10.0                          10      65000
4      seven                   9.0                           6      70000
5      three                   7.0                          10      62000
6        ten                   8.0                           7      72000
7     eleven                   7.0                           8      80000

In [15]:
#for converting word to numeric
from word2number import w2n 
  
word='one'
numeric=w2n.word_to_num(word)
print(numeric)

1


In [16]:
x=len(hir.experience)
exp=[]
for i in range(x):
    #print(hir.experience[i])
    numeric=w2n.word_to_num(hir.experience[i])
    exp.append(numeric)
    #print(numeric)
exp
    

[0, 0, 5, 2, 7, 3, 10, 11]

In [17]:
for i in range(len(exp)):
    hir.at[i,'experience']=exp[i]
hir.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: object

In [18]:
hir

experience  test_score_out_of_10  interview_score(out of 10)  salary($)
0          0                   8.0                           9      50000
1          0                   8.0                           6      45000
2          5                   6.0                           7      60000
3          2                  10.0                          10      65000
4          7                   9.0                           6      70000
5          3                   7.0                          10      62000
6         10                   8.0                           7      72000
7         11                   7.0                           8      80000

In [20]:
#calling linear regresson 
reg1=linear_model.LinearRegression()
reg1.fit(hir[['experience','test_score_out_of_10','interview_score(out of 10)']],hir['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
reg1.predict([[2,9,6]])

array([53205.96797671])

In [22]:
reg1.predict([[12,10,10]])

array([92002.18340611])