In [4]:
#1d Array
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2d Array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a[:0]

array([], shape=(0, 3), dtype=int32)

In [9]:
#masking in nparrays
a=np.zeros((3,4))
#a=np.zeros((rows and column))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#ranging in nparray
a=np.arange(10,40,5)
#np.arange(start,end,interval)
a

array([10, 15, 20, 25, 30, 35])

In [13]:
#linspacing in python
a=np.linspace(5,6,10)

In [14]:
a

array([5.        , 5.11111111, 5.22222222, 5.33333333, 5.44444444,
       5.55555556, 5.66666667, 5.77777778, 5.88888889, 6.        ])

In [15]:
#filling araay with similar number
a=np.full((3,4),5)

In [16]:
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
#filling array with random number
a= np.random.random((3,2))

In [20]:
a

array([[0.64389657, 0.91103197],
       [0.04294825, 0.02522178],
       [0.51638777, 0.08350369]])

In [21]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [3]:
#here ndim retuns dimension of array
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [7]:
#here a.dtype returns type elements in array
a=np.array([[1,2,3],[4,5,6]])
a1=np.array([[1,2,3],[4,5,'6']])
print(a.dtype,a1.dtype)

int32 <U11


In [8]:
a=np.array([1,2])
a

array([1, 2])

In [9]:
np.sum(a)

3

In [26]:
b=np.array([3,4])
print(np.subtract(a,b))
print(np.sum([a,b]))

[-2 -2]
10


In [28]:
#axis is use when particular row or column is taken
print(a,b)
np.sum([a,b],axis=1)

[1 2] [3 4]


array([3, 7])

In [29]:
print(np.divide(a,b))

[0.33333333 0.5       ]


In [31]:
print(np.multiply(a,b))

[3 8]


In [32]:
np.log(a)

array([0.        , 0.69314718])

In [33]:
np.exp(a)

array([2.71828183, 7.3890561 ])

In [34]:
np.sin(a)

array([0.84147098, 0.90929743])

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684])

In [36]:
np.tan(a)

array([ 1.55740772, -2.18503986])

In [42]:
#element wise comparison
a=[1,2,3]
b=[4,5,6]

print(np.equal(a,b))
#here array_equal() compare whole array
print(np.array_equal(a,b))

[False False False]
False


In [45]:
a=[5,7,9]
print(np.min(a),'min')
print(np.mean(a),'mean')
print(np.median(a),'median')
print(np.corrcoef(a),'corelation coefficient')
print(np.std(a),'standard deviation')
print(np.max(a))

5 min
7.0 mean
7.0 median
1.0 corelation coefficient
1.632993161855452 standard deviation
9


In [47]:
a=np.array([[1,2,3],[5,6,7]])


In [48]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [55]:
b=np.array([[0,9,8],[9,8,7]])

In [56]:
b

array([[0, 9, 8],
       [9, 8, 7]])

In [57]:
np.sum([a,b],axis=1)

array([[ 6,  8, 10],
       [ 9, 17, 15]])

In [66]:
print(a[:1,:0])

[]


In [5]:
#concatenaton in nparray in 2d
a=np.array([[1,2,3],[4,5,6],[0,9,8]])
b=np.array([[1,2,3],[4,5,6],[4,5,6]])
print(np.concatenate([a,b],axis=1))
print(np.concatenate([a,b],axis=0))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [0 9 8 4 5 6]]
[[1 2 3]
 [4 5 6]
 [0 9 8]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [14]:
#here axis=0 basically means vertically
print(np.stack([a,b],axis=0))
print(np.vstack([a,b]))      #vstack is us to stack whole array vertically


[[[1 2 3]
  [4 5 6]
  [0 9 8]]

 [[1 2 3]
  [4 5 6]
  [4 5 6]]]
[[1 2 3]
 [4 5 6]
 [0 9 8]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [15]:
#here  axis=1 basically means horzontall
print(np.stack([a,b],axis=1))
print(np.hstack([a,b])) #here hstack is use to stack whole array horizontally

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[0 9 8]
  [4 5 6]]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [0 9 8 4 5 6]]


In [18]:
q=np.array([[1,2,3],[4,5,6]])
u=np.array([[8,7,4],[5,9,0]])

In [20]:
np.vstack([q,u])

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 4],
       [5, 9, 0]])

In [21]:
np.stack([a,b])

array([[[1, 2, 3],
        [4, 5, 6],
        [0, 9, 8]],

       [[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]]])

In [32]:
#splitting of array
#np.split(array,index/list,axis)axis=0 for row and axis=1 for row
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.split(a,2,0))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [40]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.split(a,1,0))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3],
       [4, 5, 6]])]


In [41]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.split(a,3,1))

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [49]:
# while using split when we use list instead index row wise
print(a)
print(np.split(a,[1,2],0))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [53]:
a[2:]

array([], shape=(0, 3), dtype=int32)

In [54]:
a[1:2]

array([[4, 5, 6]])

In [55]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# while using split when we use list instead index column wise
print(a)
print(np.split(a,[1,2],1))

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [58]:
a[:,1:2]

array([[2],
       [5]])

In [57]:
a[:,:1]

array([[1],
       [4]])

In [59]:
a[:,2:]

array([[3],
       [6]])

In [80]:
#adavntages of numpy list/array over list
import numpy as np
import sys
l=range(1000)
print(l)
print("size of list :- ",sys.getsizeof(1)*len(l))

a=np.array(range(1000))
print("size of numpy list :- ",a.size*a.itemsize)


range(0, 1000)
size of list :-  28000
size of numpy list :-  4000


In [1]:
#speed of numpyarray/list and basic list
import time
import numpy as np
def usinglist():
    t1=time.time() #starting initial time
    x=range(100000)
    y=range(100000)
    z=[x[i]+y[i] for i in range(len(x))]
    return time.time()-t1
def usingnp():
    t1=time.time() #starting initial time
    a=np.array(range(100000))
    b=np.array(range(100000))
    z=a+b
    return time.time()-t1

listtime=usinglist()
nptime=usingnp()
print('list time taken :- ',listtime,' numpy time taken :- ',nptime)
print("in this ex ",listtime/nptime,'numpy is faster')

list time taken :-  0.02503180503845215  numpy time taken :-  0.02842235565185547
in this ex  0.8807083179545684 numpy is faster
